config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "home#index"

  get 'home/index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resources :articles do
  	resources :comments
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true
	validates :text, presence: true
	has_many :comments

	def subject
		title
	end

	def last_comment
		comments.last
	end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller? 
 
  private 
   
  def configure_permitted_parameters 
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password,:username) }
  end  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create, :destroy, :edit]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def create
    @article = Article.new(article_params)
    
    if @article.save
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end    
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
 before_filter :authenticate_user!, :only => [:new, :create]

  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def term
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/create.html.erb
<h1>Thank you!</h1>

<a href="/articles">Show all articles</a> <br />

<%= link_to 'Show all articles', articles_path %>

app/views/articles/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-3 col-sm-3 col-xs-0">
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">


			<h1>Edit article</h1>

			<%= form_for :article, url: article_path(@article), method: :put do |f| %>
			
			<p>
				<%= f.label :title %> <br />
				<label class="sr-only" for="title">Title</label>
				<%= f.text_field :title, autofocus: true, class: 'form-control', placeholder: 'Title' %>
				<br />
			</p>

			<p>
				<%= f.label :text %> <br />
				<label class="sr-only" for="message">Text</label>
				<%= f.text_area :text, class: 'form-control', placeholder: 'Text', rows: 6 %>
			</p>

			<p>
			    <%= f.submit 'Save edit', class: 'btn btn-success btn-md' %>
			</p>

			<% end %>

    	</div>
  	</div>
</div>

app/views/articles/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 col-sm-8 col-xs-12">
            
			<h1>Latest Posts</h1>

			 <% @articles.each do |article| %>
			    <h2><%= link_to "#{article.title}", article_path(article) %> </h2>

			    	<p>
						<%= link_to 'Show', article_path(article) %> |
						<%= link_to 'Edit', edit_article_path(article) %> |
						<%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?'} %>
					</p>

			    <hr />

			<% end %>
    	</div>
  	</div>
</div>

app/views/articles/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-3 col-sm-3 col-xs-0">
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">


			<h1>New article</h1>

			<%= form_for :article, url: articles_path do |f| %>
			
			<p>
				<%= f.label :title %> <br />
				<label class="sr-only" for="title">Title</label>
				<%= f.text_field :title, autofocus: true, class: 'form-control', placeholder: 'Title' %>
				<br />
			</p>

			<p>
				<%= f.label :text %> <br />
				<label class="sr-only" for="message">Text</label>
				<%= f.text_area :text, class: 'form-control', placeholder: 'Text', rows: 6 %>
			</p>

			<p>
			    <%= f.submit 'Post it now!', class: 'btn btn-success btn-md' %>
			</p>

			<% end %>

    	</div>
  	</div>
</div>

app/views/articles/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 col-sm-8 col-xs-12">

			<h1><%= @article.title %></h1>
			
			<p>
				<%= @article.text %>
			</p>

			<hr>

			<h4>Comments</h4>
			<% @article.comments.each do |comment| %>
				<p>
					<i> <%= comment.author %> said:	</i><br />
					<%= comment.body %>

				</p>
				<br />
			<% end %>

			<h5>Add comment:</h5>
			<p>
			<%= form_for([@article, @article.comments.build]) do |f| %>
				<p>
					<%= f.label :author %> <br />
					<%= f.text_field :author %>
				</p>

				<p>
					<%= f.label :body %> <br />
					<label class="sr-only" for="message">Comment</label>
					<%= f.text_area :body, class: 'form-control', placeholder: 'Text', rows: 3 %>
				</p>

				<p>
					<%= f.submit 'Comment!', class: 'btn btn-success btn-md' %>
				</p>
			</p>

			<% end %>

		</div>
	</div>
</div>

app/views/contacts/create.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 col-sm-3 col-xs-0">
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">

			<h1>Thanks!</h1>

    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 col-sm-3 col-xs-0">
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">

      <h1><%= t('contacts.contact_us') %></h1>
 
      <br />

      <%= form_for :contact, url: contacts_path do |f| %>

        <% if @contact && @contact.errors.any? %>

          <p>
            <% @contact.errors.full_messages.each do |msg| %>
              <li>
                <%= msg %>
              </li>
              <% end %>
          </p>
          <% end %>

            <p>
              <label class="sr-only" for="email">Email</label>
              <%= f.text_field :email, autofocus: true, class: 'form-control', placeholder: 'Email' %>
            </p>

            <p>
              <label class="sr-only" for="message">Message</label>
              <%= f.text_area :message, class: 'form-control', placeholder: 'Message', rows: 5 %>
            </p>

            <div class="text-right">
              <%= f.submit 'Send Message', class: 'btn btn-primary btn-md' %>
            </div>

            <% end %>

    </div>
  </div>
</div>

app/views/home/index.html.erb
<br />
<center>
	<h1>
		Hello!
	</h1>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link data-require="bootstrap@3.3.7" data-semver="3.3.7" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" /> 

    <script data-require="bootstrap@3.3.7" data-semver="3.3.7" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>
  <body>


<nav class="navbar navbar-inverse navbar-fixed-top" >
    <div class="container-fluid" >
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">RoR Simple Blog</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/articles">All Posts <span class="sr-only">(current)</span></a></li>
          <li><a href="/articles/new">New Post</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Others <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/terms">Terms</a></li>
              <li><a href="/about">About</a></li>
              <li><a href="/contacts">Contacts</a></li>
            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>

          <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Your account</a></li>
                <li role="separator" class="divider"></li>
                <li><%=link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
              </ul>
          </li>
        
        <% else %>

          <li><%= link_to 'Sign up', new_user_registration_path %></li>  
          <li><%= link_to 'Log In', new_user_session_path %></li> |  


        <% end %>
         
        </ul>
      </div>

     </div>
</nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>


  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 col-sm-3 col-xs-0">
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">

			<h1>About us</h1>

    </div>
  </div>
</div>



app/views/pages/terms.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 col-sm-3 col-xs-0">
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">

			<h1>Terms of Service</h1>

    </div>
  </div>
</div>



